Iter15
w1nsec/collector pull request #18
Opened 2023-11-03 17:25 UTC by w1nsec

2023-11-03 22:52 UTC, w1nsec commented
Не до конца понял, как именно необходимо реализовать ТЗ по данному инкременту.

Как в итоге реализовано:

1. generator - собирает метрики, кладет в storage
Так как по ТЗ старые и новые метрики (gopsutil) должны собираться в отдельных горутинах, то добавил в storage mutex для безопасного доступа к его данным
из стораджа, все метрики собираются и передаются скопом (слайс указателей на метрики) в канал.
Таким образом, в storage хранятся последние значения метрик, в канале - все собранные метрики

2. limiter - создает пул воркеров (по ограничению RATE_LIMIT)
После этого происходит запуск тикитера из пакета time.
При получении сигнала из тикетера, всем воркерам отправляется сигнал о начале работы

3. worker - отвечает за чтение из канала с собранными метриками и отправку серверу
- в случае неудачи, пишет ошибку в канал ошибок
- в случае успеха, пишет в канал успешных состояний отправки

4. валидатор ошибок - считывает сообщения из канала "ошибок" и "успехов"
- при получении сообщения из канала "ошибок", проверяем текущее количество идущих подряд ошибок, если сравнивается с максимальным, завершает контекст
- при получении сообщения из канала "успехов", количество текущих ошибок обнуляется
Максимальное количество ошибок увеличено в количество воркеров, так как воркеры будут стартовать одновременно (при наличии в канале метрик для отправки)

Есть несколько вопросов, с которыми 100% нужна помощь:
1. Какого размера должен быть канал с собранными метриками? Должен ли он зависить от  количества воркеров (RATE_LIMIT)?
2. Как правильно ожидать завершения горутин для generator, limiter, validateErrors? Стоит ли для этого использовать `<-ctx.Done()` вместо `wg.Wait()`?  (agent.go, line 202)

2023-11-12 18:11 UTC, popoffvg requested changes

2023-11-12 18:11 UTC, popoffvg commented on internal/agent/agent.go
> +	metricsChannel := make(chan []*metrics.Metrics, 100)
[major]

Использование буферизованного канала не обосновано здесь. 

Если наша система справляется с нагрузкой, то буфер не нужен. Если не справляется, то то буфер не поможет. 

Использование буферизованного канала диктуется алгоритмом (не должна выполняться блокировка). В остальных случаях нужно использовать небуферизованный канал.

2023-11-12 18:11 UTC, popoffvg commented on internal/agent/agent_workers.go
> +				return
[major] 

Завершаешь обработку ошибку и вместе с ней все приложение.

2023-11-12 18:11 UTC, popoffvg commented on internal/agent/agent_workers.go
> +	c.L.Lock()
[major]

Использование Cond излишне. Достаточно `for job := range jobs`. Если jobs не хватило на всех воркеров, то они начнут отправлять запросы не дожидаясь cond.

2023-11-12 18:11 UTC, popoffvg commented on internal/agent/agent.go
> +	newCtx, cancel := context.WithCancel(ctx)
[minor]

лучше называть стандартно ctx и err не боясь маскировать переменные, мнешь путаницы будет. 

А нестандартное название оставлять, когда нужно одновременное существование двух переменных

2023-11-12 18:11 UTC, popoffvg commented on internal/agent/agent.go
> +	//<-ctx.Done()
Да, т.к. доотправлять значения необязательно. Если бы нужно было дожидаться завершения отправки последних метрик, то просто контекстом не обойтись

2023-11-12 18:11 UTC, popoffvg commented on internal/agent/agent.go
> +	metrics map[string]metrics.MyMetrics
[minor]

Тогда стоит убрать?

2023-11-12 18:11 UTC, popoffvg commented on internal/agent/agent.go
> +		defer cancel()
[minor]

Cancel отдельно вызывать не стоит. Работа validateErrors завершится только тогда, когда контекст будет завершен

2023-11-12 18:11 UTC, popoffvg commented on internal/agent/agent_workers.go
> +			if errors.Is(err, syscall.ECONNREFUSED) {
[minor]

retry стоило сделать отдельной функцией с сигнатурой `retry(fn () error, attemts int, retryableErrs ...error)`

2023-11-12 18:11 UTC, popoffvg commented on internal/config/agent/agent_config.go
> +	if err == nil {
[minor] 
Лучше избегать веток с `err == nil`, т.к. при беглом просмотре ожидаешь `err != nil`. 

Тут можно инвертировать:
```go
args.ReportInterval, err = strconv.Atoi(os.Getenv("REPORT_INTERVAL"))
 	if err != nil {
 	     args.ReportInterval = defaultValue
 	}
```

2023-11-12 18:11 UTC, popoffvg commented on cmd/agent/agent_main.go
> +		syscall.SIGINT, syscall.SIGTERM, syscall.SIGKILL, os.Interrupt)
[major]

SIGKILL не стоит обрабатывать, т.к. это сигнал немедленного завершения процесса. Нужно позволить ОС убить процесс, т.к. скорее всего его работа мешает нормальному функционированию. Например, пришел oom killer.

2023-11-12 18:11 UTC, popoffvg commented on internal/storage/memstorage/memstorage.go
> +func (ms MemStorage) GetMetric(ctx context.Context, mName string, mType string) (*metrics.Metrics, error) {
[major]

Лучше для компонентов приложения делать ресивер указателем, чтобы  не копировать структуру каждый раз при вызове метода

2023-11-13 18:14 UTC, w1nsec commented on internal/storage/memstorage/memstorage.go
> +func (ms MemStorage) GetMetric(ctx context.Context, mName string, mType string) (*metrics.Metrics, error) {
Действительно, почему-то думал, что когда данные не изменяются, то не следует использовать указатели.
Прочитал https://github.com/golang/go/wiki/CodeReviewComments#receiver-type, не прав, спасибо за помощь

2023-11-13 18:16 UTC, w1nsec commented on internal/agent/agent_workers.go
> +	c.L.Lock()
Но тогда ведь потеряется смысл в reportInterval, разве нет?

2023-11-13 18:21 UTC, w1nsec commented on cmd/agent/agent_main.go
> +		syscall.SIGINT, syscall.SIGTERM, syscall.SIGKILL, os.Interrupt)
Исправил

2023-11-13 18:37 UTC, w1nsec commented on internal/agent/agent.go
> +	metrics map[string]metrics.MyMetrics
В ходе работы переписывал функции отправки в соответствии с заданием, в итоге, оставил как сами функции, так и поле, чтобы функции не  вызывали ошибок (legacy)

2023-11-13 18:42 UTC, w1nsec commented on internal/agent/agent_workers.go
> +				return
Не понимаю. Я завершаю функцию, так количество ошибок превысило максимально-допустимое количество.

2023-11-13 18:46 UTC, w1nsec commented on internal/agent/agent_workers.go
> +				return
После выхода из функции отрабатывает `defer cancel()` из `internal/agent/agent.go` `line 191`

```go
	go func() {
		// second exec: cancel current context
		defer cancel()
		// first exec:  close current goroutine, decrease wg Counter
		defer wg.Done()
		agent.validateErrors(ctx)

	}()
```

С помощью контекста передастя завершение в остальные запущенные в горутинах функции. Как только функции завершатся, завершится приложение

2023-11-13 19:03 UTC, w1ns3c commented on internal/agent/agent.go
> +		defer cancel()
Почему? Не понимаю, могу попросить объяснить?
Я вызываю `cancel()` чтобы завершить другие горутины

2023-11-13 19:09 UTC, w1nsec commented on internal/agent/agent.go
> +	metricsChannel := make(chan []*metrics.Metrics, 100)
Я использовал здесь буферезированный канал именно потому, что по заданию указано, чтобы сбор метрик производился по указанному расписанию (pollInterval). Если поменять на небуферезированный канал, то агент будет висеть, пока, данный из него не прочитают воркеры (что в соответствии с заданием должно происходить по reportInterval).
Если pollInterval будет к примеру 3сек, а report 15сек, то метрики должны собраться 5 раз, а после уже начать отправляться.

Или я неправильно понимаю задание?

2023-11-15 20:38 UTC, w1nsec commented
@popoffvg посмотришь появившиеся вопросы?

2023-11-16 06:34 UTC, popoffvg commented on internal/agent/agent_workers.go
> +				return
Context завершается > все функции должны завершиться, т.к. ты передаешь в них контекст > выполнятся все wg.Done > wg.Wait завешается вместе с приложением

2023-11-16 06:46 UTC, popoffvg commented on internal/agent/agent_workers.go
> +	c.L.Lock()
Нет, можно реализовать отправку данных через [паттерн fun-out](https://www.educative.io/answers/what-is-the-fan-out-fan-in-pattern-in-golang).

reportINterval - мы должны отправлять данные каждые N сек, к примеру. 
Возможны 2 ситуации: 
- обработка пакета метрик выполняется меньше времени интервала. Тогда воркер-пул не нужен и нужна только одна горутина
- обработка пакета метрик выполняется дольше времени интервала. В этом случае воркер пул работает как буфер и пока время обработки запроса меньше или равно N * Wn (где Wn - кол-во воркеров) система будет отправлять данные. 

Как только время обработки запроса превысило N * Wn, то мы должны терять данные.

В отправке данных через равные промежутки времени смысла нет.

2023-11-16 06:52 UTC, popoffvg commented on internal/agent/agent_workers.go
> +				return
> Я завершаю функцию, так количество ошибок превысило максимально-допустимое количество.

Это неправильное решение.

Представим ситуацию, когда наш агент собирает метрики с реального сервера, а может и не с одного. 
Мы не уследили за хранилищем метрик и оно упало. Место кончилось, к примеру. 

В этот момент все агенты перестают работать. После починки мы должны его перезапустить. При том, что они все упали это неочивидно.

Ладно если один сервер, а если их 10-ки? Лучше проектировать приложение сразу таким образом, чтобы не создавалась лишняя работа. 

В случае если мы не хотим отправлять запросы на сервер при большом кол-ве ошибок нужно использовать паттерн [circuit breaker](https://microservices.io/patterns/reliability/circuit-breaker.html). Он позволяет прекращать отправку запросов на какое-то время.

2023-11-16 06:53 UTC, popoffvg commented on internal/agent/agent.go
> +	metricsChannel := make(chan []*metrics.Metrics, 100)
Постарался ответить в [комментарии](https://github.com/w1nsec/collector/pull/18#discussion_r1395220015)

2023-11-16 06:54 UTC, popoffvg commented on internal/agent/agent.go
> +		defer cancel()
Постарался ответить в [комментарии](https://github.com/w1nsec/collector/pull/18#discussion_r1395224037)

2023-11-16 16:59 UTC, w1nsec commented on internal/agent/agent_workers.go
> +	c.L.Lock()
Так в задании сказано об ограничении отправляемых  данных
![task_15](https://github.com/w1nsec/collector/assets/144123683/4e81a910-26e4-4668-b1cb-72388e5c9ae5)

2023-11-16 19:31 UTC, w1nsec commented on internal/agent/agent_workers.go
> +	c.L.Lock()
> Если jobs не хватило на всех воркеров, то они начнут отправлять запросы не дожидаясь cond.

Они каждый отправлят по одной метрике максимум и уснут до следующего reportInterval (эквивалентно cond)

2023-11-16 19:35 UTC, w1ns3c commented on internal/agent/agent_workers.go
> +	c.L.Lock()
В схеме с Fan-Out worker'ы просто начнут отправлять батчи метрик, как только только те будут передаваться в канал. Не совсем вижу отличие от схемы с `cond`,  видимо, просто антипатерн

2023-11-16 19:40 UTC, w1nsec commented on internal/agent/agent_workers.go
> +				return
> Это неправильное решение.
![image](https://github.com/w1nsec/collector/assets/144123683/1acf046e-4ce6-4a2c-9e6a-90e901dab410)

Там по ТЗ из 13 инкремента было указано что количество повторов ограничено, вот и подумал, что после приложение закрывается

2023-11-16 19:43 UTC, w1nsec commented on internal/agent/agent_workers.go
> +			if errors.Is(err, syscall.ECONNREFUSED) {
Не могу это представить при работе с горутинами, если обрабатывать err из воркера, то его еще и стартовать потом надо...
Пока, кажетстя, не способен реализовать

2023-11-16 19:45 UTC, w1nsec commented on internal/agent/agent.go
> +	//<-ctx.Done()
Исправил

2023-11-25 19:07 UTC, merged